export const phase3Categories = [
  {
    "id": "P301",
    "name": "子音→母音リンキング",
    "example": "pick it up / turn it off",
    "point": "語末子音を次の語頭母音へつなげて聞く",
    "count": 10
  },
  {
    "id": "P302",
    "name": "母音→母音リンキング",
    "example": "go out / see it",
    "point": "/w/・/j/ の渡り音を手掛かりに母音間を聞く",
    "count": 10
  },
  {
    "id": "P303",
    "name": "隣接子音の連結",
    "example": "big game / good day",
    "point": "同じ・近い子音を二度破裂させず一まとまりで聞く",
    "count": 10
  },
  {
    "id": "P304",
    "name": "弱形・シュワー",
    "example": "him・her・his / to・for・of・at",
    "point": "代名詞の目的格・所有格と前置詞などの弱形を復元する",
    "count": 10
  },
  {
    "id": "P305",
    "name": "文の強弱・リズム",
    "example": "content words / function words",
    "point": "内容語の強勢と機能語の弱化から意味の核をつかむ",
    "count": 10
  },
  {
    "id": "P306",
    "name": "T・Dのフラップ",
    "example": "get it / a lot of",
    "point": "母音間の /t, d/ が日本語のラ行に近い弾き音になる",
    "count": 10
  },
  {
    "id": "P307",
    "name": "音の脱落",
    "example": "next day / old man",
    "point": "子音群で落ちやすい /t, d/ を文脈から補う",
    "count": 10
  },
  {
    "id": "P308",
    "name": "同化・音の融合",
    "example": "did you / don’t you",
    "point": "隣り合う音が相手に近づく、または新しい音に融合する",
    "count": 10
  },
  {
    "id": "P309",
    "name": "頻出リダクション",
    "example": "gonna / wanna / hafta",
    "point": "会話で頻出するまとまりを一つの音の塊として認識する",
    "count": 10
  }
];

export const phase3Questions = [
  {
    "id": "P301-01",
    "categoryId": "P301",
    "category": "子音→母音リンキング",
    "learningPoint": "語末子音を次の語頭母音へつなげて聞く",
    "questionType": "文の二択",
    "sentence": "Pick it up before you leave.",
    "japanese": "出かける前にそれを拾って。",
    "targetChunk": "pick it up",
    "soundChange": "pick‿it‿up：/k/ と /t/ が次の母音へ連結",
    "prompt": "自然な音声に含まれた文を選ぶ",
    "distractor": "聞き取り注意：pick it up",
    "wordCount": 6,
    "audioFile": "audio/phase3/P301-01.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P301-02",
    "categoryId": "P301",
    "category": "子音→母音リンキング",
    "learningPoint": "語末子音を次の語頭母音へつなげて聞く",
    "questionType": "空欄補充",
    "sentence": "Turn it off when you finish.",
    "japanese": "終わったらそれを消して。",
    "targetChunk": "turn it off",
    "soundChange": "turn‿it‿off：/n/ と /t/ が次の母音へ連結",
    "prompt": "聞こえた語句を空欄に入れる",
    "distractor": "聞き取り注意：turn it off",
    "wordCount": 6,
    "audioFile": "audio/phase3/P301-02.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P301-03",
    "categoryId": "P301",
    "category": "子音→母音リンキング",
    "learningPoint": "語末子音を次の語頭母音へつなげて聞く",
    "questionType": "語数判定",
    "sentence": "Take it out of the box.",
    "japanese": "箱からそれを取り出して。",
    "targetChunk": "take it out",
    "soundChange": "take‿it‿out：/k/ と /t/ が次の母音へ連結",
    "prompt": "聞こえた語数を選ぶ",
    "distractor": "5語 / 7語",
    "wordCount": 6,
    "audioFile": "audio/phase3/P301-03.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P301-04",
    "categoryId": "P301",
    "category": "子音→母音リンキング",
    "learningPoint": "語末子音を次の語頭母音へつなげて聞く",
    "questionType": "チップ復元",
    "sentence": "Put it on the table.",
    "japanese": "それをテーブルに置いて。",
    "targetChunk": "put it on",
    "soundChange": "put‿it‿on：語境界を切らずに連結",
    "prompt": "語句チップを並べて文を復元する",
    "distractor": "it / on / the / table / Put",
    "wordCount": 5,
    "audioFile": "audio/phase3/P301-04.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P301-05",
    "categoryId": "P301",
    "category": "子音→母音リンキング",
    "learningPoint": "語末子音を次の語頭母音へつなげて聞く",
    "questionType": "変化判定",
    "sentence": "Read it aloud for us.",
    "japanese": "私たちのためにそれを音読して。",
    "targetChunk": "read it aloud",
    "soundChange": "read‿it‿aloud：/d/ と /t/ が次の母音へ連結",
    "prompt": "起きている音の変化を選ぶ",
    "distractor": "変化なし / 単語を一語ずつ区切る",
    "wordCount": 5,
    "audioFile": "audio/phase3/P301-05.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P301-06",
    "categoryId": "P301",
    "category": "子音→母音リンキング",
    "learningPoint": "語末子音を次の語頭母音へつなげて聞く",
    "questionType": "文の二択",
    "sentence": "Send it over tonight.",
    "japanese": "今夜それを送って。",
    "targetChunk": "send it over",
    "soundChange": "send‿it‿over：/d/ と /t/ が次の母音へ連結",
    "prompt": "自然な音声に含まれた文を選ぶ",
    "distractor": "聞き取り注意：send it over",
    "wordCount": 4,
    "audioFile": "audio/phase3/P301-06.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P301-07",
    "categoryId": "P301",
    "category": "子音→母音リンキング",
    "learningPoint": "語末子音を次の語頭母音へつなげて聞く",
    "questionType": "空欄補充",
    "sentence": "Leave it at the desk.",
    "japanese": "それを受付に置いて。",
    "targetChunk": "leave it at",
    "soundChange": "leave‿it‿at：/v/ と /t/ が次の母音へ連結",
    "prompt": "聞こえた語句を空欄に入れる",
    "distractor": "聞き取り注意：leave it at",
    "wordCount": 5,
    "audioFile": "audio/phase3/P301-07.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P301-08",
    "categoryId": "P301",
    "category": "子音→母音リンキング",
    "learningPoint": "語末子音を次の語頭母音へつなげて聞く",
    "questionType": "語数判定",
    "sentence": "Check it again tomorrow.",
    "japanese": "明日もう一度確認して。",
    "targetChunk": "check it again",
    "soundChange": "check‿it‿again：/k/ と /t/ が次の母音へ連結",
    "prompt": "聞こえた語数を選ぶ",
    "distractor": "3語 / 5語",
    "wordCount": 4,
    "audioFile": "audio/phase3/P301-08.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P301-09",
    "categoryId": "P301",
    "category": "子音→母音リンキング",
    "learningPoint": "語末子音を次の語頭母音へつなげて聞く",
    "questionType": "チップ復元",
    "sentence": "Hold on a minute.",
    "japanese": "ちょっと待って。",
    "targetChunk": "hold on",
    "soundChange": "hold‿on：/d/ が次の母音へ連結",
    "prompt": "語句チップを並べて文を復元する",
    "distractor": "on / a / minute / Hold",
    "wordCount": 4,
    "audioFile": "audio/phase3/P301-09.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P301-10",
    "categoryId": "P301",
    "category": "子音→母音リンキング",
    "learningPoint": "語末子音を次の語頭母音へつなげて聞く",
    "questionType": "変化判定",
    "sentence": "Come in and sit down.",
    "japanese": "入って座って。",
    "targetChunk": "come in",
    "soundChange": "come‿in：/m/ が次の母音へ連結",
    "prompt": "起きている音の変化を選ぶ",
    "distractor": "変化なし / 単語を一語ずつ区切る",
    "wordCount": 5,
    "audioFile": "audio/phase3/P301-10.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P302-01",
    "categoryId": "P302",
    "category": "母音→母音リンキング",
    "learningPoint": "/w/・/j/ の渡り音を手掛かりに母音間を聞く",
    "questionType": "文の二択",
    "sentence": "Go out and get some air.",
    "japanese": "外に出て空気を吸って。",
    "targetChunk": "go out",
    "soundChange": "go‿(w)out：/w/ の渡り音",
    "prompt": "自然な音声に含まれた文を選ぶ",
    "distractor": "聞き取り注意：go out",
    "wordCount": 6,
    "audioFile": "audio/phase3/P302-01.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P302-02",
    "categoryId": "P302",
    "category": "母音→母音リンキング",
    "learningPoint": "/w/・/j/ の渡り音を手掛かりに母音間を聞く",
    "questionType": "空欄補充",
    "sentence": "Do it again for me.",
    "japanese": "私のためにもう一度やって。",
    "targetChunk": "do it",
    "soundChange": "do‿(w)it：/w/ の渡り音",
    "prompt": "聞こえた語句を空欄に入れる",
    "distractor": "聞き取り注意：do it",
    "wordCount": 5,
    "audioFile": "audio/phase3/P302-02.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P302-03",
    "categoryId": "P302",
    "category": "母音→母音リンキング",
    "learningPoint": "/w/・/j/ の渡り音を手掛かりに母音間を聞く",
    "questionType": "語数判定",
    "sentence": "I agree with your idea.",
    "japanese": "あなたの考えに賛成です。",
    "targetChunk": "I agree",
    "soundChange": "I‿(j)agree：/j/ の渡り音",
    "prompt": "聞こえた語数を選ぶ",
    "distractor": "4語 / 6語",
    "wordCount": 5,
    "audioFile": "audio/phase3/P302-03.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P302-04",
    "categoryId": "P302",
    "category": "母音→母音リンキング",
    "learningPoint": "/w/・/j/ の渡り音を手掛かりに母音間を聞く",
    "questionType": "チップ復元",
    "sentence": "We asked for some help.",
    "japanese": "私たちは助けを求めた。",
    "targetChunk": "we asked",
    "soundChange": "we‿(j)asked：/j/ の渡り音",
    "prompt": "語句チップを並べて文を復元する",
    "distractor": "asked / for / some / help / We",
    "wordCount": 5,
    "audioFile": "audio/phase3/P302-04.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P302-05",
    "categoryId": "P302",
    "category": "母音→母音リンキング",
    "learningPoint": "/w/・/j/ の渡り音を手掛かりに母音間を聞く",
    "questionType": "変化判定",
    "sentence": "See it for yourself.",
    "japanese": "自分で確かめて。",
    "targetChunk": "see it",
    "soundChange": "see‿(j)it：/j/ の渡り音",
    "prompt": "起きている音の変化を選ぶ",
    "distractor": "変化なし / 単語を一語ずつ区切る",
    "wordCount": 4,
    "audioFile": "audio/phase3/P302-05.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P302-06",
    "categoryId": "P302",
    "category": "母音→母音リンキング",
    "learningPoint": "/w/・/j/ の渡り音を手掛かりに母音間を聞く",
    "questionType": "文の二択",
    "sentence": "She always arrives early.",
    "japanese": "彼女はいつも早く着く。",
    "targetChunk": "she always",
    "soundChange": "she‿(j)always：/j/ の渡り音",
    "prompt": "自然な音声に含まれた文を選ぶ",
    "distractor": "聞き取り注意：she always",
    "wordCount": 4,
    "audioFile": "audio/phase3/P302-06.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P302-07",
    "categoryId": "P302",
    "category": "母音→母音リンキング",
    "learningPoint": "/w/・/j/ の渡り音を手掛かりに母音間を聞く",
    "questionType": "空欄補充",
    "sentence": "Go over the details.",
    "japanese": "詳細を確認して。",
    "targetChunk": "go over",
    "soundChange": "go‿(w)over：/w/ の渡り音",
    "prompt": "聞こえた語句を空欄に入れる",
    "distractor": "聞き取り注意：go over",
    "wordCount": 4,
    "audioFile": "audio/phase3/P302-07.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P302-08",
    "categoryId": "P302",
    "category": "母音→母音リンキング",
    "learningPoint": "/w/・/j/ の渡り音を手掛かりに母音間を聞く",
    "questionType": "語数判定",
    "sentence": "Who is at the door?",
    "japanese": "ドアの所にいるのは誰？",
    "targetChunk": "who is",
    "soundChange": "who‿(w)is：/w/ の渡り音",
    "prompt": "聞こえた語数を選ぶ",
    "distractor": "4語 / 6語",
    "wordCount": 5,
    "audioFile": "audio/phase3/P302-08.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P302-09",
    "categoryId": "P302",
    "category": "母音→母音リンキング",
    "learningPoint": "/w/・/j/ の渡り音を手掛かりに母音間を聞く",
    "questionType": "チップ復元",
    "sentence": "They are already here.",
    "japanese": "彼らはもうここにいる。",
    "targetChunk": "they are",
    "soundChange": "they‿(j)are：/j/ の渡り音",
    "prompt": "語句チップを並べて文を復元する",
    "distractor": "are / already / here / They",
    "wordCount": 4,
    "audioFile": "audio/phase3/P302-09.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P302-10",
    "categoryId": "P302",
    "category": "母音→母音リンキング",
    "learningPoint": "/w/・/j/ の渡り音を手掛かりに母音間を聞く",
    "questionType": "変化判定",
    "sentence": "Try it one more time.",
    "japanese": "もう一度やってみて。",
    "targetChunk": "try it",
    "soundChange": "try‿(j)it：/j/ の渡り音",
    "prompt": "起きている音の変化を選ぶ",
    "distractor": "変化なし / 単語を一語ずつ区切る",
    "wordCount": 5,
    "audioFile": "audio/phase3/P302-10.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P303-01",
    "categoryId": "P303",
    "category": "隣接子音の連結",
    "learningPoint": "同じ・近い子音を二度破裂させず一まとまりで聞く",
    "questionType": "文の二択",
    "sentence": "The big game starts tonight.",
    "japanese": "大きな試合は今夜始まる。",
    "targetChunk": "big game",
    "soundChange": "big‿game：/g/ を一度だけ長めに保持",
    "prompt": "自然な音声に含まれた文を選ぶ",
    "distractor": "聞き取り注意：big game",
    "wordCount": 5,
    "audioFile": "audio/phase3/P303-01.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P303-02",
    "categoryId": "P303",
    "category": "隣接子音の連結",
    "learningPoint": "同じ・近い子音を二度破裂させず一まとまりで聞く",
    "questionType": "空欄補充",
    "sentence": "We had two good days.",
    "japanese": "私たちは良い日を二日過ごした。",
    "targetChunk": "good days",
    "soundChange": "good‿days：/d/ を重ねて一度に解放",
    "prompt": "聞こえた語句を空欄に入れる",
    "distractor": "聞き取り注意：good days",
    "wordCount": 5,
    "audioFile": "audio/phase3/P303-02.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P303-03",
    "categoryId": "P303",
    "category": "隣接子音の連結",
    "learningPoint": "同じ・近い子音を二度破裂させず一まとまりで聞く",
    "questionType": "語数判定",
    "sentence": "Take care on the stairs.",
    "japanese": "階段では気をつけて。",
    "targetChunk": "take care",
    "soundChange": "take‿care：/k/ を重ねて連結",
    "prompt": "聞こえた語数を選ぶ",
    "distractor": "4語 / 6語",
    "wordCount": 5,
    "audioFile": "audio/phase3/P303-03.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P303-04",
    "categoryId": "P303",
    "category": "隣接子音の連結",
    "learningPoint": "同じ・近い子音を二度破裂させず一まとまりで聞く",
    "questionType": "チップ復元",
    "sentence": "Keep practicing every day.",
    "japanese": "毎日練習を続けて。",
    "targetChunk": "keep practicing",
    "soundChange": "keep‿practicing：/p/ を重ねて連結",
    "prompt": "語句チップを並べて文を復元する",
    "distractor": "practicing / every / day / Keep",
    "wordCount": 4,
    "audioFile": "audio/phase3/P303-04.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P303-05",
    "categoryId": "P303",
    "category": "隣接子音の連結",
    "learningPoint": "同じ・近い子音を二度破裂させず一まとまりで聞く",
    "questionType": "変化判定",
    "sentence": "The red door is open.",
    "japanese": "赤いドアは開いている。",
    "targetChunk": "red door",
    "soundChange": "red‿door：/d/ を一度にまとめる",
    "prompt": "起きている音の変化を選ぶ",
    "distractor": "変化なし / 単語を一語ずつ区切る",
    "wordCount": 5,
    "audioFile": "audio/phase3/P303-05.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P303-06",
    "categoryId": "P303",
    "category": "隣接子音の連結",
    "learningPoint": "同じ・近い子音を二度破裂させず一まとまりで聞く",
    "questionType": "文の二択",
    "sentence": "Stop playing with that.",
    "japanese": "それで遊ぶのをやめて。",
    "targetChunk": "stop playing",
    "soundChange": "stop‿playing：/p/ を一度にまとめる",
    "prompt": "自然な音声に含まれた文を選ぶ",
    "distractor": "聞き取り注意：stop playing",
    "wordCount": 4,
    "audioFile": "audio/phase3/P303-06.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P303-07",
    "categoryId": "P303",
    "category": "隣接子音の連結",
    "learningPoint": "同じ・近い子音を二度破裂させず一まとまりで聞く",
    "questionType": "空欄補充",
    "sentence": "A black cat crossed the road.",
    "japanese": "黒猫が道路を渡った。",
    "targetChunk": "black cat",
    "soundChange": "black‿cat：/k/ を重ねて連結",
    "prompt": "聞こえた語句を空欄に入れる",
    "distractor": "聞き取り注意：black cat",
    "wordCount": 6,
    "audioFile": "audio/phase3/P303-07.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P303-08",
    "categoryId": "P303",
    "category": "隣接子音の連結",
    "learningPoint": "同じ・近い子音を二度破裂させず一まとまりで聞く",
    "questionType": "語数判定",
    "sentence": "This bus stop is crowded.",
    "japanese": "このバス停は混んでいる。",
    "targetChunk": "bus stop",
    "soundChange": "bus‿stop：/s/ を切らずに保持",
    "prompt": "聞こえた語数を選ぶ",
    "distractor": "4語 / 6語",
    "wordCount": 5,
    "audioFile": "audio/phase3/P303-08.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P303-09",
    "categoryId": "P303",
    "category": "隣接子音の連結",
    "learningPoint": "同じ・近い子音を二度破裂させず一まとまりで聞く",
    "questionType": "チップ復元",
    "sentence": "She felt tired today.",
    "japanese": "彼女は今日疲れていた。",
    "targetChunk": "felt tired",
    "soundChange": "felt‿tired：/t/ を重ねて連結",
    "prompt": "語句チップを並べて文を復元する",
    "distractor": "felt / tired / today / She",
    "wordCount": 4,
    "audioFile": "audio/phase3/P303-09.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P303-10",
    "categoryId": "P303",
    "category": "隣接子音の連結",
    "learningPoint": "同じ・近い子音を二度破裂させず一まとまりで聞く",
    "questionType": "変化判定",
    "sentence": "The top player scored again.",
    "japanese": "トップ選手がまた得点した。",
    "targetChunk": "top player",
    "soundChange": "top‿player：/p/ を一度だけ解放",
    "prompt": "起きている音の変化を選ぶ",
    "distractor": "変化なし / 単語を一語ずつ区切る",
    "wordCount": 5,
    "audioFile": "audio/phase3/P303-10.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P304-01",
    "categoryId": "P304",
    "category": "弱形・シュワー",
    "learningPoint": "代名詞の目的格・所有格と前置詞などの弱形を復元する",
    "questionType": "文の二択",
    "sentence": "Tell him about the meeting.",
    "japanese": "彼に会議のことを伝えて。",
    "targetChunk": "him",
    "soundChange": "him /hɪm/ → /ɪm/：/h/ 脱落を伴う弱形",
    "prompt": "自然な音声に含まれた文を選ぶ",
    "distractor": "聞き取り注意：him",
    "wordCount": 5,
    "audioFile": "audio/phase3/P304-01.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P304-02",
    "categoryId": "P304",
    "category": "弱形・シュワー",
    "learningPoint": "代名詞の目的格・所有格と前置詞などの弱形を復元する",
    "questionType": "空欄補充",
    "sentence": "I saw her at the station.",
    "japanese": "駅で彼女を見かけた。",
    "targetChunk": "her",
    "soundChange": "her /hɝː/ → /ər/：/h/ 脱落を伴う弱形",
    "prompt": "聞こえた語句を空欄に入れる",
    "distractor": "聞き取り注意：her",
    "wordCount": 6,
    "audioFile": "audio/phase3/P304-02.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P304-03",
    "categoryId": "P304",
    "category": "弱形・シュワー",
    "learningPoint": "代名詞の目的格・所有格と前置詞などの弱形を復元する",
    "questionType": "語数判定",
    "sentence": "That is his new car.",
    "japanese": "あれは彼の新しい車です。",
    "targetChunk": "his",
    "soundChange": "his /hɪz/ → /ɪz/：/h/ 脱落を伴う弱形",
    "prompt": "聞こえた語数を選ぶ",
    "distractor": "4語 / 6語",
    "wordCount": 5,
    "audioFile": "audio/phase3/P304-03.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P304-04",
    "categoryId": "P304",
    "category": "弱形・シュワー",
    "learningPoint": "代名詞の目的格・所有格と前置詞などの弱形を復元する",
    "questionType": "チップ復元",
    "sentence": "Give them a few minutes.",
    "japanese": "彼らに数分あげて。",
    "targetChunk": "them",
    "soundChange": "them /ðem/ → /ðəm/：母音がシュワー化",
    "prompt": "語句チップを並べて文を復元する",
    "distractor": "them / a / few / minutes / Give",
    "wordCount": 5,
    "audioFile": "audio/phase3/P304-04.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P304-05",
    "categoryId": "P304",
    "category": "弱形・シュワー",
    "learningPoint": "代名詞の目的格・所有格と前置詞などの弱形を復元する",
    "questionType": "変化判定",
    "sentence": "We are going to the store.",
    "japanese": "私たちは店へ行くところです。",
    "targetChunk": "to",
    "soundChange": "to /tuː/ → /tə/：前置詞の弱形",
    "prompt": "起きている音の変化を選ぶ",
    "distractor": "変化なし / 単語を一語ずつ区切る",
    "wordCount": 6,
    "audioFile": "audio/phase3/P304-05.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P304-06",
    "categoryId": "P304",
    "category": "弱形・シュワー",
    "learningPoint": "代名詞の目的格・所有格と前置詞などの弱形を復元する",
    "questionType": "文の二択",
    "sentence": "This gift is for my sister.",
    "japanese": "この贈り物は姉へのものです。",
    "targetChunk": "for",
    "soundChange": "for /fɔːr/ → /fər/：前置詞の弱形",
    "prompt": "自然な音声に含まれた文を選ぶ",
    "distractor": "聞き取り注意：for",
    "wordCount": 6,
    "audioFile": "audio/phase3/P304-06.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P304-07",
    "categoryId": "P304",
    "category": "弱形・シュワー",
    "learningPoint": "代名詞の目的格・所有格と前置詞などの弱形を復元する",
    "questionType": "空欄補充",
    "sentence": "I need a cup of coffee.",
    "japanese": "コーヒーを一杯ください。",
    "targetChunk": "of",
    "soundChange": "of /ʌv/ → /əv, ə/：前置詞の弱形",
    "prompt": "聞こえた語句を空欄に入れる",
    "distractor": "聞き取り注意：of",
    "wordCount": 6,
    "audioFile": "audio/phase3/P304-07.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P304-08",
    "categoryId": "P304",
    "category": "弱形・シュワー",
    "learningPoint": "代名詞の目的格・所有格と前置詞などの弱形を復元する",
    "questionType": "語数判定",
    "sentence": "Meet me at the entrance.",
    "japanese": "入口で会いましょう。",
    "targetChunk": "at",
    "soundChange": "at /æt/ → /ət/：前置詞の弱形",
    "prompt": "聞こえた語数を選ぶ",
    "distractor": "4語 / 6語",
    "wordCount": 5,
    "audioFile": "audio/phase3/P304-08.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P304-09",
    "categoryId": "P304",
    "category": "弱形・シュワー",
    "learningPoint": "代名詞の目的格・所有格と前置詞などの弱形を復元する",
    "questionType": "チップ復元",
    "sentence": "She came from the office.",
    "japanese": "彼女はオフィスから来た。",
    "targetChunk": "from",
    "soundChange": "from /frʌm/ → /frəm/：前置詞の弱形",
    "prompt": "語句チップを並べて文を復元する",
    "distractor": "came / from / the / office / She",
    "wordCount": 5,
    "audioFile": "audio/phase3/P304-09.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P304-10",
    "categoryId": "P304",
    "category": "弱形・シュワー",
    "learningPoint": "代名詞の目的格・所有格と前置詞などの弱形を復元する",
    "questionType": "変化判定",
    "sentence": "Bread and butter, please.",
    "japanese": "パンとバターをお願いします。",
    "targetChunk": "and",
    "soundChange": "and /ænd/ → /ən, n/：接続詞の弱形",
    "prompt": "起きている音の変化を選ぶ",
    "distractor": "変化なし / 単語を一語ずつ区切る",
    "wordCount": 4,
    "audioFile": "audio/phase3/P304-10.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P305-01",
    "categoryId": "P305",
    "category": "文の強弱・リズム",
    "learningPoint": "内容語の強勢と機能語の弱化から意味の核をつかむ",
    "questionType": "文の二択",
    "sentence": "The CHILD bought a NEW red BIKE.",
    "japanese": "その子は新しい赤い自転車を買った。",
    "targetChunk": "child / new / bike",
    "soundChange": "内容語 CHILD・NEW・BIKE に強勢",
    "prompt": "自然な音声に含まれた文を選ぶ",
    "distractor": "聞き取り注意：child / new / bike",
    "wordCount": 7,
    "audioFile": "audio/phase3/P305-01.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P305-02",
    "categoryId": "P305",
    "category": "文の強弱・リズム",
    "learningPoint": "内容語の強勢と機能語の弱化から意味の核をつかむ",
    "questionType": "空欄補充",
    "sentence": "Please SEND me the FILE by FOUR.",
    "japanese": "4時までにファイルを送って。",
    "targetChunk": "send / file / four",
    "soundChange": "意味の核 SEND・FILE・FOUR に強勢",
    "prompt": "聞こえた語句を空欄に入れる",
    "distractor": "聞き取り注意：send / file / four",
    "wordCount": 7,
    "audioFile": "audio/phase3/P305-02.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P305-03",
    "categoryId": "P305",
    "category": "文の強弱・リズム",
    "learningPoint": "内容語の強勢と機能語の弱化から意味の核をつかむ",
    "questionType": "語数判定",
    "sentence": "We NEED to FIND a CHEAP hotel.",
    "japanese": "安いホテルを探す必要がある。",
    "targetChunk": "need / find / cheap / hotel",
    "soundChange": "内容語が拍を作り機能語は短くなる",
    "prompt": "聞こえた語数を選ぶ",
    "distractor": "6語 / 8語",
    "wordCount": 7,
    "audioFile": "audio/phase3/P305-03.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P305-04",
    "categoryId": "P305",
    "category": "文の強弱・リズム",
    "learningPoint": "内容語の強勢と機能語の弱化から意味の核をつかむ",
    "questionType": "チップ復元",
    "sentence": "She LEFT her KEYS on the TRAIN.",
    "japanese": "彼女は電車に鍵を忘れた。",
    "targetChunk": "left / keys / train",
    "soundChange": "LEFT・KEYS・TRAIN に強勢",
    "prompt": "語句チップを並べて文を復元する",
    "distractor": "LEFT / her / KEYS / on / the / TRAIN / She",
    "wordCount": 7,
    "audioFile": "audio/phase3/P305-04.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P305-05",
    "categoryId": "P305",
    "category": "文の強弱・リズム",
    "learningPoint": "内容語の強勢と機能語の弱化から意味の核をつかむ",
    "questionType": "変化判定",
    "sentence": "I ORDERED the SOUP and a SALAD.",
    "japanese": "スープとサラダを注文した。",
    "targetChunk": "ordered / soup / salad",
    "soundChange": "内容語間をほぼ等間隔で発音",
    "prompt": "起きている音の変化を選ぶ",
    "distractor": "変化なし / 単語を一語ずつ区切る",
    "wordCount": 7,
    "audioFile": "audio/phase3/P305-05.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P305-06",
    "categoryId": "P305",
    "category": "文の強弱・リズム",
    "learningPoint": "内容語の強勢と機能語の弱化から意味の核をつかむ",
    "questionType": "文の二択",
    "sentence": "They MOVED to a HOUSE near SCHOOL.",
    "japanese": "彼らは学校近くの家に引っ越した。",
    "targetChunk": "moved / house / school",
    "soundChange": "MOVED・HOUSE・SCHOOL に強勢",
    "prompt": "自然な音声に含まれた文を選ぶ",
    "distractor": "聞き取り注意：moved / house / school",
    "wordCount": 7,
    "audioFile": "audio/phase3/P305-06.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P305-07",
    "categoryId": "P305",
    "category": "文の強弱・リズム",
    "learningPoint": "内容語の強勢と機能語の弱化から意味の核をつかむ",
    "questionType": "空欄補充",
    "sentence": "Can you CALL me AFTER LUNCH?",
    "japanese": "昼食後に電話してくれる？",
    "targetChunk": "call / after / lunch",
    "soundChange": "CALL・AFTER・LUNCH が強勢核",
    "prompt": "聞こえた語句を空欄に入れる",
    "distractor": "聞き取り注意：call / after / lunch",
    "wordCount": 6,
    "audioFile": "audio/phase3/P305-07.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P305-08",
    "categoryId": "P305",
    "category": "文の強弱・リズム",
    "learningPoint": "内容語の強勢と機能語の弱化から意味の核をつかむ",
    "questionType": "語数判定",
    "sentence": "The MEETING starts at HALF past NINE.",
    "japanese": "会議は9時半に始まる。",
    "targetChunk": "meeting / half / nine",
    "soundChange": "時刻を担う語に強勢",
    "prompt": "聞こえた語数を選ぶ",
    "distractor": "6語 / 8語",
    "wordCount": 7,
    "audioFile": "audio/phase3/P305-08.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P305-09",
    "categoryId": "P305",
    "category": "文の強弱・リズム",
    "learningPoint": "内容語の強勢と機能語の弱化から意味の核をつかむ",
    "questionType": "チップ復元",
    "sentence": "He DROVE through the RAIN all NIGHT.",
    "japanese": "彼は一晩中雨の中を運転した。",
    "targetChunk": "drove / rain / night",
    "soundChange": "DROVE・RAIN・NIGHT に強勢",
    "prompt": "語句チップを並べて文を復元する",
    "distractor": "DROVE / through / the / RAIN / all / NIGHT / He",
    "wordCount": 7,
    "audioFile": "audio/phase3/P305-09.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P305-10",
    "categoryId": "P305",
    "category": "文の強弱・リズム",
    "learningPoint": "内容語の強勢と機能語の弱化から意味の核をつかむ",
    "questionType": "変化判定",
    "sentence": "I REALLY LIKE your NEW idea.",
    "japanese": "あなたの新しい案が本当に好き。",
    "targetChunk": "really / like / new / idea",
    "soundChange": "焦点語を強く、機能語を弱く発音",
    "prompt": "起きている音の変化を選ぶ",
    "distractor": "変化なし / 単語を一語ずつ区切る",
    "wordCount": 6,
    "audioFile": "audio/phase3/P305-10.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P306-01",
    "categoryId": "P306",
    "category": "T・Dのフラップ",
    "learningPoint": "母音間の /t, d/ が日本語のラ行に近い弾き音になる",
    "questionType": "文の二択",
    "sentence": "I got it at the market.",
    "japanese": "市場でそれを手に入れた。",
    "targetChunk": "got it",
    "soundChange": "got it：/t/ → [ɾ]",
    "prompt": "自然な音声に含まれた文を選ぶ",
    "distractor": "聞き取り注意：got it",
    "wordCount": 6,
    "audioFile": "audio/phase3/P306-01.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P306-02",
    "categoryId": "P306",
    "category": "T・Dのフラップ",
    "learningPoint": "母音間の /t, d/ が日本語のラ行に近い弾き音になる",
    "questionType": "空欄補充",
    "sentence": "Put it on the table.",
    "japanese": "それをテーブルに置いて。",
    "targetChunk": "put it",
    "soundChange": "put it：/t/ → [ɾ]",
    "prompt": "聞こえた語句を空欄に入れる",
    "distractor": "聞き取り注意：put it",
    "wordCount": 5,
    "audioFile": "audio/phase3/P306-02.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P306-03",
    "categoryId": "P306",
    "category": "T・Dのフラップ",
    "learningPoint": "母音間の /t, d/ が日本語のラ行に近い弾き音になる",
    "questionType": "語数判定",
    "sentence": "What are you doing?",
    "japanese": "何をしているの？",
    "targetChunk": "what are",
    "soundChange": "what are：/t/ → [ɾ]",
    "prompt": "聞こえた語数を選ぶ",
    "distractor": "3語 / 5語",
    "wordCount": 4,
    "audioFile": "audio/phase3/P306-03.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P306-04",
    "categoryId": "P306",
    "category": "T・Dのフラップ",
    "learningPoint": "母音間の /t, d/ が日本語のラ行に近い弾き音になる",
    "questionType": "チップ復元",
    "sentence": "We need a lot of water.",
    "japanese": "水がたくさん必要です。",
    "targetChunk": "lot of water",
    "soundChange": "lot of / water：/t/ → [ɾ]",
    "prompt": "語句チップを並べて文を復元する",
    "distractor": "need / a / lot / of / water / We",
    "wordCount": 6,
    "audioFile": "audio/phase3/P306-04.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P306-05",
    "categoryId": "P306",
    "category": "T・Dのフラップ",
    "learningPoint": "母音間の /t, d/ が日本語のラ行に近い弾き音になる",
    "questionType": "変化判定",
    "sentence": "She wrote it in a letter.",
    "japanese": "彼女はそれを手紙に書いた。",
    "targetChunk": "wrote it",
    "soundChange": "wrote it：/t/ → [ɾ]",
    "prompt": "起きている音の変化を選ぶ",
    "distractor": "変化なし / 単語を一語ずつ区切る",
    "wordCount": 6,
    "audioFile": "audio/phase3/P306-05.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P306-06",
    "categoryId": "P306",
    "category": "T・Dのフラップ",
    "learningPoint": "母音間の /t, d/ が日本語のラ行に近い弾き音になる",
    "questionType": "文の二択",
    "sentence": "Get out of the car.",
    "japanese": "車から降りて。",
    "targetChunk": "get out",
    "soundChange": "get out：/t/ → [ɾ]",
    "prompt": "自然な音声に含まれた文を選ぶ",
    "distractor": "聞き取り注意：get out",
    "wordCount": 5,
    "audioFile": "audio/phase3/P306-06.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P306-07",
    "categoryId": "P306",
    "category": "T・Dのフラップ",
    "learningPoint": "母音間の /t, d/ が日本語のラ行に近い弾き音になる",
    "questionType": "空欄補充",
    "sentence": "I bought a better computer.",
    "japanese": "より良いパソコンを買った。",
    "targetChunk": "better computer",
    "soundChange": "better：/t/ → [ɾ]",
    "prompt": "聞こえた語句を空欄に入れる",
    "distractor": "聞き取り注意：better computer",
    "wordCount": 5,
    "audioFile": "audio/phase3/P306-07.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P306-08",
    "categoryId": "P306",
    "category": "T・Dのフラップ",
    "learningPoint": "母音間の /t, d/ が日本語のラ行に近い弾き音になる",
    "questionType": "語数判定",
    "sentence": "He waited at the station.",
    "japanese": "彼は駅で待った。",
    "targetChunk": "waited at",
    "soundChange": "waited at：/t, d/ の連続がフラップ化",
    "prompt": "聞こえた語数を選ぶ",
    "distractor": "4語 / 6語",
    "wordCount": 5,
    "audioFile": "audio/phase3/P306-08.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P306-09",
    "categoryId": "P306",
    "category": "T・Dのフラップ",
    "learningPoint": "母音間の /t, d/ が日本語のラ行に近い弾き音になる",
    "questionType": "チップ復元",
    "sentence": "That is a beautiful city.",
    "japanese": "あれは美しい街です。",
    "targetChunk": "beautiful city",
    "soundChange": "beautiful / city：強勢のない母音間 /t/ → [ɾ]",
    "prompt": "語句チップを並べて文を復元する",
    "distractor": "is / a / beautiful / city / That",
    "wordCount": 5,
    "audioFile": "audio/phase3/P306-09.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P306-10",
    "categoryId": "P306",
    "category": "T・Dのフラップ",
    "learningPoint": "母音間の /t, d/ が日本語のラ行に近い弾き音になる",
    "questionType": "変化判定",
    "sentence": "I met her at a party.",
    "japanese": "パーティーで彼女に会った。",
    "targetChunk": "at a party",
    "soundChange": "at a：/t/ → [ɾ]",
    "prompt": "起きている音の変化を選ぶ",
    "distractor": "変化なし / 単語を一語ずつ区切る",
    "wordCount": 6,
    "audioFile": "audio/phase3/P306-10.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P307-01",
    "categoryId": "P307",
    "category": "音の脱落",
    "learningPoint": "子音群で落ちやすい /t, d/ を文脈から補う",
    "questionType": "文の二択",
    "sentence": "I went there last night.",
    "japanese": "昨夜そこへ行った。",
    "targetChunk": "last night",
    "soundChange": "last night：/t/ が脱落しやすい",
    "prompt": "自然な音声に含まれた文を選ぶ",
    "distractor": "聞き取り注意：last night",
    "wordCount": 5,
    "audioFile": "audio/phase3/P307-01.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P307-02",
    "categoryId": "P307",
    "category": "音の脱落",
    "learningPoint": "子音群で落ちやすい /t, d/ を文脈から補う",
    "questionType": "空欄補充",
    "sentence": "The next day was sunny.",
    "japanese": "翌日は晴れだった。",
    "targetChunk": "next day",
    "soundChange": "next day：/t/ が脱落しやすい",
    "prompt": "聞こえた語句を空欄に入れる",
    "distractor": "聞き取り注意：next day",
    "wordCount": 5,
    "audioFile": "audio/phase3/P307-02.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P307-03",
    "categoryId": "P307",
    "category": "音の脱落",
    "learningPoint": "子音群で落ちやすい /t, d/ を文脈から補う",
    "questionType": "語数判定",
    "sentence": "She held my hand.",
    "japanese": "彼女は私の手を握った。",
    "targetChunk": "held my",
    "soundChange": "held my：/d/ が弱化・脱落しやすい",
    "prompt": "聞こえた語数を選ぶ",
    "distractor": "3語 / 5語",
    "wordCount": 4,
    "audioFile": "audio/phase3/P307-03.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P307-04",
    "categoryId": "P307",
    "category": "音の脱落",
    "learningPoint": "子音群で落ちやすい /t, d/ を文脈から補う",
    "questionType": "チップ復元",
    "sentence": "He left the door open.",
    "japanese": "彼はドアを開けたままにした。",
    "targetChunk": "left the",
    "soundChange": "left the：子音群で /t/ が弱くなる",
    "prompt": "語句チップを並べて文を復元する",
    "distractor": "left / the / door / open / He",
    "wordCount": 5,
    "audioFile": "audio/phase3/P307-04.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P307-05",
    "categoryId": "P307",
    "category": "音の脱落",
    "learningPoint": "子音群で落ちやすい /t, d/ を文脈から補う",
    "questionType": "変化判定",
    "sentence": "We must go now.",
    "japanese": "もう行かなければならない。",
    "targetChunk": "must go",
    "soundChange": "must go：/t/ が脱落しやすい",
    "prompt": "起きている音の変化を選ぶ",
    "distractor": "変化なし / 単語を一語ずつ区切る",
    "wordCount": 4,
    "audioFile": "audio/phase3/P307-05.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P307-06",
    "categoryId": "P307",
    "category": "音の脱落",
    "learningPoint": "子音群で落ちやすい /t, d/ を文脈から補う",
    "questionType": "文の二択",
    "sentence": "I do not know the answer.",
    "japanese": "答えが分かりません。",
    "targetChunk": "do not know",
    "soundChange": "not know：/t/ が脱落しやすい",
    "prompt": "自然な音声に含まれた文を選ぶ",
    "distractor": "聞き取り注意：do not know",
    "wordCount": 6,
    "audioFile": "audio/phase3/P307-06.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P307-07",
    "categoryId": "P307",
    "category": "音の脱落",
    "learningPoint": "子音群で落ちやすい /t, d/ を文脈から補う",
    "questionType": "空欄補充",
    "sentence": "She asked me twice.",
    "japanese": "彼女は私に二度尋ねた。",
    "targetChunk": "asked me",
    "soundChange": "asked me：子音群 /sktm/ が簡略化",
    "prompt": "聞こえた語句を空欄に入れる",
    "distractor": "聞き取り注意：asked me",
    "wordCount": 4,
    "audioFile": "audio/phase3/P307-07.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P307-08",
    "categoryId": "P307",
    "category": "音の脱落",
    "learningPoint": "子音群で落ちやすい /t, d/ を文脈から補う",
    "questionType": "語数判定",
    "sentence": "It was the best movie.",
    "japanese": "それが一番良い映画だった。",
    "targetChunk": "best movie",
    "soundChange": "best movie：/t/ が脱落しやすい",
    "prompt": "聞こえた語数を選ぶ",
    "distractor": "4語 / 6語",
    "wordCount": 5,
    "audioFile": "audio/phase3/P307-08.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P307-09",
    "categoryId": "P307",
    "category": "音の脱落",
    "learningPoint": "子音群で落ちやすい /t, d/ を文脈から補う",
    "questionType": "チップ復元",
    "sentence": "They found the old man.",
    "japanese": "彼らはその老人を見つけた。",
    "targetChunk": "found the",
    "soundChange": "found the：/d/ が弱化・脱落しやすい",
    "prompt": "語句チップを並べて文を復元する",
    "distractor": "found / the / old / man / They",
    "wordCount": 5,
    "audioFile": "audio/phase3/P307-09.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P307-10",
    "categoryId": "P307",
    "category": "音の脱落",
    "learningPoint": "子音群で落ちやすい /t, d/ を文脈から補う",
    "questionType": "変化判定",
    "sentence": "I kept the first prize.",
    "japanese": "私は一等賞を取っておいた。",
    "targetChunk": "first prize",
    "soundChange": "first prize：子音群で /t/ が脱落しやすい",
    "prompt": "起きている音の変化を選ぶ",
    "distractor": "変化なし / 単語を一語ずつ区切る",
    "wordCount": 5,
    "audioFile": "audio/phase3/P307-10.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P308-01",
    "categoryId": "P308",
    "category": "同化・音の融合",
    "learningPoint": "隣り合う音が相手に近づく、または新しい音に融合する",
    "questionType": "文の二択",
    "sentence": "Did you call me?",
    "japanese": "私に電話した？",
    "targetChunk": "did you",
    "soundChange": "did you：/d + j/ → /dʒ/",
    "prompt": "自然な音声に含まれた文を選ぶ",
    "distractor": "聞き取り注意：did you",
    "wordCount": 4,
    "audioFile": "audio/phase3/P308-01.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P308-02",
    "categoryId": "P308",
    "category": "同化・音の融合",
    "learningPoint": "隣り合う音が相手に近づく、または新しい音に融合する",
    "questionType": "空欄補充",
    "sentence": "Would you like some tea?",
    "japanese": "紅茶はいかが？",
    "targetChunk": "would you",
    "soundChange": "would you：/d + j/ → /dʒ/",
    "prompt": "聞こえた語句を空欄に入れる",
    "distractor": "聞き取り注意：would you",
    "wordCount": 5,
    "audioFile": "audio/phase3/P308-02.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P308-03",
    "categoryId": "P308",
    "category": "同化・音の融合",
    "learningPoint": "隣り合う音が相手に近づく、または新しい音に融合する",
    "questionType": "語数判定",
    "sentence": "Don't you know her?",
    "japanese": "彼女を知らないの？",
    "targetChunk": "don't you",
    "soundChange": "don't you：/t + j/ → /tʃ/",
    "prompt": "聞こえた語数を選ぶ",
    "distractor": "3語 / 5語",
    "wordCount": 4,
    "audioFile": "audio/phase3/P308-03.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P308-04",
    "categoryId": "P308",
    "category": "同化・音の融合",
    "learningPoint": "隣り合う音が相手に近づく、または新しい音に融合する",
    "questionType": "チップ復元",
    "sentence": "Could you open the door?",
    "japanese": "ドアを開けてくれる？",
    "targetChunk": "could you",
    "soundChange": "could you：/d + j/ → /dʒ/",
    "prompt": "語句チップを並べて文を復元する",
    "distractor": "you / open / the / door / Could",
    "wordCount": 5,
    "audioFile": "audio/phase3/P308-04.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P308-05",
    "categoryId": "P308",
    "category": "同化・音の融合",
    "learningPoint": "隣り合う音が相手に近づく、または新しい音に融合する",
    "questionType": "変化判定",
    "sentence": "I miss you already.",
    "japanese": "もうあなたが恋しい。",
    "targetChunk": "miss you",
    "soundChange": "miss you：/s + j/ → /ʃ/",
    "prompt": "起きている音の変化を選ぶ",
    "distractor": "変化なし / 単語を一語ずつ区切る",
    "wordCount": 4,
    "audioFile": "audio/phase3/P308-05.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P308-06",
    "categoryId": "P308",
    "category": "同化・音の融合",
    "learningPoint": "隣り合う音が相手に近づく、または新しい音に融合する",
    "questionType": "文の二択",
    "sentence": "Bless you.",
    "japanese": "お大事に。",
    "targetChunk": "bless you",
    "soundChange": "bless you：/s + j/ → /ʃ/",
    "prompt": "自然な音声に含まれた文を選ぶ",
    "distractor": "聞き取り注意：bless you",
    "wordCount": 2,
    "audioFile": "audio/phase3/P308-06.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P308-07",
    "categoryId": "P308",
    "category": "同化・音の融合",
    "learningPoint": "隣り合う音が相手に近づく、または新しい音に融合する",
    "questionType": "空欄補充",
    "sentence": "As you know, we are ready.",
    "japanese": "ご存じのとおり準備はできています。",
    "targetChunk": "as you",
    "soundChange": "as you：/z + j/ → /ʒ/",
    "prompt": "聞こえた語句を空欄に入れる",
    "distractor": "聞き取り注意：as you",
    "wordCount": 6,
    "audioFile": "audio/phase3/P308-07.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P308-08",
    "categoryId": "P308",
    "category": "同化・音の融合",
    "learningPoint": "隣り合う音が相手に近づく、または新しい音に融合する",
    "questionType": "語数判定",
    "sentence": "This year went quickly.",
    "japanese": "今年はあっという間だった。",
    "targetChunk": "this year",
    "soundChange": "this year：/s + j/ が /ʃ/ に近づく",
    "prompt": "聞こえた語数を選ぶ",
    "distractor": "3語 / 5語",
    "wordCount": 4,
    "audioFile": "audio/phase3/P308-08.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P308-09",
    "categoryId": "P308",
    "category": "同化・音の融合",
    "learningPoint": "隣り合う音が相手に近づく、または新しい音に融合する",
    "questionType": "チップ復元",
    "sentence": "Ten boys joined the team.",
    "japanese": "10人の少年がチームに入った。",
    "targetChunk": "ten boys",
    "soundChange": "ten boys：/n/ → /m/（両唇音の前）",
    "prompt": "語句チップを並べて文を復元する",
    "distractor": "boys / joined / the / team / Ten",
    "wordCount": 5,
    "audioFile": "audio/phase3/P308-09.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P308-10",
    "categoryId": "P308",
    "category": "同化・音の融合",
    "learningPoint": "隣り合う音が相手に近づく、または新しい音に融合する",
    "questionType": "変化判定",
    "sentence": "Green paper is on the desk.",
    "japanese": "緑の紙は机の上です。",
    "targetChunk": "green paper",
    "soundChange": "green paper：/n/ → /m/（両唇音の前）",
    "prompt": "起きている音の変化を選ぶ",
    "distractor": "変化なし / 単語を一語ずつ区切る",
    "wordCount": 6,
    "audioFile": "audio/phase3/P308-10.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P309-01",
    "categoryId": "P309",
    "category": "頻出リダクション",
    "learningPoint": "会話で頻出するまとまりを一つの音の塊として認識する",
    "questionType": "文の二択",
    "sentence": "I am going to call you.",
    "japanese": "あなたに電話するつもりです。",
    "targetChunk": "going to",
    "soundChange": "going to → gonna",
    "prompt": "自然な音声に含まれた文を選ぶ",
    "distractor": "聞き取り注意：going to",
    "wordCount": 6,
    "audioFile": "audio/phase3/P309-01.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P309-02",
    "categoryId": "P309",
    "category": "頻出リダクション",
    "learningPoint": "会話で頻出するまとまりを一つの音の塊として認識する",
    "questionType": "空欄補充",
    "sentence": "Do you want to come?",
    "japanese": "一緒に来たい？",
    "targetChunk": "want to",
    "soundChange": "want to → wanna",
    "prompt": "聞こえた語句を空欄に入れる",
    "distractor": "聞き取り注意：want to",
    "wordCount": 5,
    "audioFile": "audio/phase3/P309-02.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P309-03",
    "categoryId": "P309",
    "category": "頻出リダクション",
    "learningPoint": "会話で頻出するまとまりを一つの音の塊として認識する",
    "questionType": "語数判定",
    "sentence": "I have to leave now.",
    "japanese": "もう出なければならない。",
    "targetChunk": "have to",
    "soundChange": "have to → hafta",
    "prompt": "聞こえた語数を選ぶ",
    "distractor": "4語 / 6語",
    "wordCount": 5,
    "audioFile": "audio/phase3/P309-03.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P309-04",
    "categoryId": "P309",
    "category": "頻出リダクション",
    "learningPoint": "会話で頻出するまとまりを一つの音の塊として認識する",
    "questionType": "チップ復元",
    "sentence": "Let me check it.",
    "japanese": "確認させて。",
    "targetChunk": "let me",
    "soundChange": "let me → lemme",
    "prompt": "語句チップを並べて文を復元する",
    "distractor": "me / check / it / Let",
    "wordCount": 4,
    "audioFile": "audio/phase3/P309-04.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P309-05",
    "categoryId": "P309",
    "category": "頻出リダクション",
    "learningPoint": "会話で頻出するまとまりを一つの音の塊として認識する",
    "questionType": "変化判定",
    "sentence": "Give me a minute.",
    "japanese": "少し時間をください。",
    "targetChunk": "give me",
    "soundChange": "give me → gimme",
    "prompt": "起きている音の変化を選ぶ",
    "distractor": "変化なし / 単語を一語ずつ区切る",
    "wordCount": 4,
    "audioFile": "audio/phase3/P309-05.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P309-06",
    "categoryId": "P309",
    "category": "頻出リダクション",
    "learningPoint": "会話で頻出するまとまりを一つの音の塊として認識する",
    "questionType": "文の二択",
    "sentence": "I have got to go.",
    "japanese": "もう行かなければ。",
    "targetChunk": "got to",
    "soundChange": "got to → gotta",
    "prompt": "自然な音声に含まれた文を選ぶ",
    "distractor": "聞き取り注意：got to",
    "wordCount": 5,
    "audioFile": "audio/phase3/P309-06.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P309-07",
    "categoryId": "P309",
    "category": "頻出リダクション",
    "learningPoint": "会話で頻出するまとまりを一つの音の塊として認識する",
    "questionType": "空欄補充",
    "sentence": "You should have told me.",
    "japanese": "私に言うべきだった。",
    "targetChunk": "should have",
    "soundChange": "should have → shoulda /ʃʊdə/",
    "prompt": "聞こえた語句を空欄に入れる",
    "distractor": "聞き取り注意：should have",
    "wordCount": 5,
    "audioFile": "audio/phase3/P309-07.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P309-08",
    "categoryId": "P309",
    "category": "頻出リダクション",
    "learningPoint": "会話で頻出するまとまりを一つの音の塊として認識する",
    "questionType": "語数判定",
    "sentence": "I could have helped you.",
    "japanese": "あなたを助けられたのに。",
    "targetChunk": "could have",
    "soundChange": "could have → coulda /kʊdə/",
    "prompt": "聞こえた語数を選ぶ",
    "distractor": "4語 / 6語",
    "wordCount": 5,
    "audioFile": "audio/phase3/P309-08.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P309-09",
    "categoryId": "P309",
    "category": "頻出リダクション",
    "learningPoint": "会話で頻出するまとまりを一つの音の塊として認識する",
    "questionType": "チップ復元",
    "sentence": "What are you doing?",
    "japanese": "何をしているの？",
    "targetChunk": "what are you",
    "soundChange": "what are you → whaddaya（速い会話）",
    "prompt": "語句チップを並べて文を復元する",
    "distractor": "are / you / doing / What",
    "wordCount": 4,
    "audioFile": "audio/phase3/P309-09.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  },
  {
    "id": "P309-10",
    "categoryId": "P309",
    "category": "頻出リダクション",
    "learningPoint": "会話で頻出するまとまりを一つの音の塊として認識する",
    "questionType": "変化判定",
    "sentence": "It is kind of strange.",
    "japanese": "ちょっと変だね。",
    "targetChunk": "kind of",
    "soundChange": "kind of → kinda",
    "prompt": "起きている音の変化を選ぶ",
    "distractor": "変化なし / 単語を一語ずつ区切る",
    "wordCount": 5,
    "audioFile": "audio/phase3/P309-10.wav",
    "status": "Draft audio",
    "note": "音声合成版。正式版では狙った音変化を再現した収録音声に差し替える。"
  }
];
